---
ciscoConfigCopyMIB: 1.3.6.1.4.1.9.9.96
ciscoConfigCopyMIBObjects: 1.3.6.1.4.1.9.9.96.1
ccCopy: 1.3.6.1.4.1.9.9.96.1.1
ccCopyTable: 1.3.6.1.4.1.9.9.96.1.1.1
ccCopyEntry: 1.3.6.1.4.1.9.9.96.1.1.1.1
ccCopyIndex: 1.3.6.1.4.1.9.9.96.1.1.1.1.1
ccCopyProtocol: 1.3.6.1.4.1.9.9.96.1.1.1.1.2
ccCopySourceFileType: 1.3.6.1.4.1.9.9.96.1.1.1.1.3
ccCopyDestFileType: 1.3.6.1.4.1.9.9.96.1.1.1.1.4
ccCopyServerAddress: 1.3.6.1.4.1.9.9.96.1.1.1.1.5
ccCopyFileName: 1.3.6.1.4.1.9.9.96.1.1.1.1.6
ccCopyUserName: 1.3.6.1.4.1.9.9.96.1.1.1.1.7
ccCopyUserPassword: 1.3.6.1.4.1.9.9.96.1.1.1.1.8
ccCopyNotificationOnCompletion: 1.3.6.1.4.1.9.9.96.1.1.1.1.9
ccCopyState: 1.3.6.1.4.1.9.9.96.1.1.1.1.10
ccCopyTimeStarted: 1.3.6.1.4.1.9.9.96.1.1.1.1.11
ccCopyTimeCompleted: 1.3.6.1.4.1.9.9.96.1.1.1.1.12
ccCopyFailCause: 1.3.6.1.4.1.9.9.96.1.1.1.1.13
ccCopyEntryRowStatus: 1.3.6.1.4.1.9.9.96.1.1.1.1.14
ccCopyServerAddressType: 1.3.6.1.4.1.9.9.96.1.1.1.1.15
ccCopyServerAddressRev1: 1.3.6.1.4.1.9.9.96.1.1.1.1.16
ccCopyErrorTable: 1.3.6.1.4.1.9.9.96.1.1.2
ccCopyErrorEntry: 1.3.6.1.4.1.9.9.96.1.1.2.1
ccCopyErrorIndex: 1.3.6.1.4.1.9.9.96.1.1.2.1.1
ccCopyErrorDeviceIpAddressType: 1.3.6.1.4.1.9.9.96.1.1.2.1.2
ccCopyErrorDeviceIpAddress: 1.3.6.1.4.1.9.9.96.1.1.2.1.3
ccCopyErrorDeviceWWN: 1.3.6.1.4.1.9.9.96.1.1.2.1.4
ccCopyErrorDescription: 1.3.6.1.4.1.9.9.96.1.1.2.1.5
ciscoConfigCopyMIBTrapPrefix: 1.3.6.1.4.1.9.9.96.2
ccCopyMIBTraps: 1.3.6.1.4.1.9.9.96.2.1
ciscoConfigCopyMIBConformance: 1.3.6.1.4.1.9.9.96.3
ccCopyMIBCompliances: 1.3.6.1.4.1.9.9.96.3.1
ccCopyMIBGroups: 1.3.6.1.4.1.9.9.96.3.2
ccCopyCompletion: 1.3.6.1.4.1.9.9.96.2.1.1

