---
ciscoL2L3IfConfigCapability: 1.3.6.1.4.1.9.7.326
ciscoL2L3IfConfigCapV12R0119E: 1.3.6.1.4.1.9.7.326.1
ciscoL2L3IfConfigCapNxOSV06R0202PN7K: 1.3.6.1.4.1.9.7.326.2
ciscoL2L3IfConfigCapNxOSV06R0201PMds: 1.3.6.1.4.1.9.7.326.3

