---
ciscoL2L3IfConfigMIB: 1.3.6.1.4.1.9.9.151
ciscoL2L3IfConfigMIBObjects: 1.3.6.1.4.1.9.9.151.1
cL2L3IfConfig: 1.3.6.1.4.1.9.9.151.1.1
cL2L3IfTable: 1.3.6.1.4.1.9.9.151.1.1.1
cL2L3IfEntry: 1.3.6.1.4.1.9.9.151.1.1.1.1
cL2L3IfModeAdmin: 1.3.6.1.4.1.9.9.151.1.1.1.1.1
cL2L3IfModeOper: 1.3.6.1.4.1.9.9.151.1.1.1.1.2
ciscoL2L3IfConfigMIBConformance: 1.3.6.1.4.1.9.9.151.3
ciscoL2L3IfConfigMIBCompliances: 1.3.6.1.4.1.9.9.151.3.1
ciscoL2L3IfConfigMIBGroups: 1.3.6.1.4.1.9.9.151.3.2

