---
ciscoVoiceApplicationsOIDMIB: 1.3.6.1.4.1.9.12.5
cvaMIBOids: 1.3.6.1.4.1.9.12.5.1
ciscoCallManager: 1.3.6.1.4.1.9.12.5.1.1
ciscoCallManagerExpress: 1.3.6.1.4.1.9.12.5.1.2
ciscoSRST: 1.3.6.1.4.1.9.12.5.1.3
ciscoBTS: 1.3.6.1.4.1.9.12.5.1.4
ciscoCSPS: 1.3.6.1.4.1.9.12.5.1.5

